// Trama's icons for the whole renderer (person's note, 1 October 2026): the same names and props as @tabler/icons-react,
// drawn woven. The main ones are Trama's own drawings (brand/tramaIcons.ts), the others Tabler's geometry with gaps.
import { TramaIcon } from "@/components/brand/TramaIcon";
import type { TramaIconName } from "@/components/brand/tramaIcons";
import { Woven, type WovenIconProps } from "./woven";
import { WOVEN_ICONS } from "./woven.generated";

export type Icon = (props: WovenIconProps) => React.JSX.Element;

const woven = (name: string, slug: string): Icon => {
  const icon = WOVEN_ICONS[name]!;
  const Component = (props: WovenIconProps) => <Woven icon={icon} slug={slug} {...props} />;
  Component.displayName = name;
  return Component;
};

const own = (name: TramaIconName): Icon => {
  const Component = ({ className, stroke, style }: WovenIconProps) => <TramaIcon name={name} className={className} stroke={stroke} style={style} />;
  Component.displayName = `Trama(${name})`;
  return Component;
};

export const IconAlertCircle = woven("IconAlertCircle", "alert-circle");
export const IconAlertTriangle = woven("IconAlertTriangle", "alert-triangle");
export const IconArchive = woven("IconArchive", "archive");
export const IconArchiveOff = woven("IconArchiveOff", "archive-off");
export const IconArrowBackUp = woven("IconArrowBackUp", "arrow-back-up");
export const IconArrowLeft = woven("IconArrowLeft", "arrow-left");
export const IconArrowNarrowLeft = woven("IconArrowNarrowLeft", "arrow-narrow-left");
export const IconArrowNarrowRight = woven("IconArrowNarrowRight", "arrow-narrow-right");
export const IconArrowUp = woven("IconArrowUp", "arrow-up");
export const IconArrowsDiagonal = woven("IconArrowsDiagonal", "arrows-diagonal");
export const IconArrowsDiagonalMinimize2 = woven("IconArrowsDiagonalMinimize2", "arrows-diagonal-minimize-2");
export const IconArrowsSort = woven("IconArrowsSort", "arrows-sort");
export const IconArrowsSplit = woven("IconArrowsSplit", "arrows-split");
export const IconAt = woven("IconAt", "at");
export const IconBan = woven("IconBan", "ban");
export const IconBellPause = woven("IconBellPause", "bell-pause");
export const IconBolt = woven("IconBolt", "bolt");
export const IconBoltFilled = woven("IconBoltFilled", "bolt-filled");
export const IconBook = woven("IconBook", "book");
export const IconBook2 = woven("IconBook2", "book-2");
export const IconBrain = own("memory");
export const IconBrandGithub = woven("IconBrandGithub", "brand-github");
export const IconBriefcase = woven("IconBriefcase", "briefcase");
export const IconBug = woven("IconBug", "bug");
export const IconBulb = woven("IconBulb", "bulb");
export const IconCheck = woven("IconCheck", "check");
export const IconChecklist = woven("IconChecklist", "checklist");
export const IconChevronDown = woven("IconChevronDown", "chevron-down");
export const IconChevronRight = woven("IconChevronRight", "chevron-right");
export const IconChevronUp = woven("IconChevronUp", "chevron-up");
export const IconCircleCheck = woven("IconCircleCheck", "circle-check");
export const IconCircleDashed = woven("IconCircleDashed", "circle-dashed");
export const IconCircleDot = woven("IconCircleDot", "circle-dot");
export const IconCircleX = woven("IconCircleX", "circle-x");
export const IconClockPause = woven("IconClockPause", "clock-pause");
export const IconCloudFilled = woven("IconCloudFilled", "cloud-filled");
export const IconCopy = woven("IconCopy", "copy");
export const IconDeviceDesktop = woven("IconDeviceDesktop", "device-desktop");
export const IconDeviceLaptop = woven("IconDeviceLaptop", "device-laptop");
export const IconDots = woven("IconDots", "dots");
export const IconExternalLink = woven("IconExternalLink", "external-link");
export const IconEye = woven("IconEye", "eye");
export const IconFile = woven("IconFile", "file");
export const IconFileCode = woven("IconFileCode", "file-code");
export const IconFileDiff = own("work");
export const IconFileText = woven("IconFileText", "file-text");
export const IconFilter = woven("IconFilter", "filter");
export const IconFlame = woven("IconFlame", "flame");
export const IconFocus2 = woven("IconFocus2", "focus-2");
export const IconFolder = woven("IconFolder", "folder");
export const IconFolderOpen = woven("IconFolderOpen", "folder-open");
export const IconFolderPlus = woven("IconFolderPlus", "folder-plus");
export const IconFolders = own("projects");
export const IconGitBranch = woven("IconGitBranch", "git-branch");
export const IconGitCommit = woven("IconGitCommit", "git-commit");
export const IconGitMerge = woven("IconGitMerge", "git-merge");
export const IconGitPullRequest = woven("IconGitPullRequest", "git-pull-request");
export const IconHandStop = woven("IconHandStop", "hand-stop");
export const IconHome = woven("IconHome", "home");
export const IconHourglass = own("waiting");
export const IconInfoCircle = woven("IconInfoCircle", "info-circle");
export const IconLanguage = woven("IconLanguage", "language");
export const IconLayoutList = woven("IconLayoutList", "layout-list");
export const IconListCheck = woven("IconListCheck", "list-check");
export const IconListDetails = woven("IconListDetails", "list-details");
export const IconLock = woven("IconLock", "lock");
export const IconLockOpen = woven("IconLockOpen", "lock-open");
export const IconMessage = woven("IconMessage", "message");
export const IconMessageCircle = woven("IconMessageCircle", "message-circle");
export const IconMessageQuestion = woven("IconMessageQuestion", "message-question");
export const IconMessages = woven("IconMessages", "messages");
export const IconMoon = woven("IconMoon", "moon");
export const IconPencil = woven("IconPencil", "pencil");
export const IconPencilPlus = woven("IconPencilPlus", "pencil-plus");
export const IconPhotoPlus = woven("IconPhotoPlus", "photo-plus");
export const IconPin = woven("IconPin", "pin");
export const IconPinned = woven("IconPinned", "pinned");
export const IconPinnedOff = woven("IconPinnedOff", "pinned-off");
export const IconPlayerPause = woven("IconPlayerPause", "player-pause");
export const IconPlayerPlay = woven("IconPlayerPlay", "player-play");
export const IconPlayerSkipForward = woven("IconPlayerSkipForward", "player-skip-forward");
export const IconPlayerStop = woven("IconPlayerStop", "player-stop");
export const IconPlayerTrackNext = woven("IconPlayerTrackNext", "player-track-next");
export const IconPlugConnected = woven("IconPlugConnected", "plug-connected");
export const IconPlus = woven("IconPlus", "plus");
export const IconRefresh = own("refresh");
export const IconRepeatOff = woven("IconRepeatOff", "repeat-off");
export const IconRosetteDiscountCheck = woven("IconRosetteDiscountCheck", "rosette-discount-check");
export const IconRotateClockwise = own("refresh");
export const IconRoute = woven("IconRoute", "route");
export const IconSchool = woven("IconSchool", "school");
export const IconSearch = woven("IconSearch", "search");
export const IconSettings = own("settings");
export const IconShieldCheck = own("rules");
export const IconShieldLock = woven("IconShieldLock", "shield-lock");
export const IconSitemap = woven("IconSitemap", "sitemap");
export const IconSparkles = woven("IconSparkles", "sparkles");
export const IconStethoscope = woven("IconStethoscope", "stethoscope");
export const IconSun = woven("IconSun", "sun");
export const IconTarget = woven("IconTarget", "target");
export const IconTelescope = woven("IconTelescope", "telescope");
export const IconTerminal2 = woven("IconTerminal2", "terminal-2");
export const IconTool = woven("IconTool", "tool");
export const IconTools = woven("IconTools", "tools");
export const IconTrash = woven("IconTrash", "trash");
export const IconUser = woven("IconUser", "user");
export const IconUserSearch = woven("IconUserSearch", "user-search");
export const IconUsers = woven("IconUsers", "users");
export const IconUsersGroup = own("teams");
export const IconX = woven("IconX", "x");
